#!/usr/bin/env bash
# Instal nginx in server

sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

# Creating index.html
echo "Hello World!" | sudo tee /var/www/html/index.html
# Testing nginx
sudo nginx -t
# reload Nginx
sudo service nginx start

