#!/usr/bin/env bash
# Instal nginx in server

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World" | sudo tee /var/www/html/index.html
# test nginx
sudo nginx -t
#reload nginx
sudo nginx reload
