#!/usr/bin/env bash
# 301 move permanently

sudo apt-get update
sudo apt-get install -y nginx

# Create index.html
echo "Hello World!" | sudo tee /var/www.html/index.html

#Redirections 
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/nmcleon permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restarting Nginx
sudo service nginx restart
