#!/usr/bin/env bash
# Configures an Nginx server as is in task 0, add -f.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"

